mex -R2018a "-IC:\Program Files\CyberGlove Systems\VirtualHand SDK\include\vhandtk"...
    "-LC:\Program Files\CyberGlove Systems\VirtualHand SDK\lib\winnt_x64\Release" ...
    -lCGS_VirtualHandCore -lCGS_VirtualHandDevice Source_mxArray_5.cpp